file_format: "1"
id: hypergolic
name: Hypergolic
type: shield
url: https://github.com/davidphilipbarr/hypergolic
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - hypergolic_left
  - hypergolic_right
