manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: filterpaper
      url-base: https://github.com/filterpaper
  projects:
    - name: zmk
#      remote: filterpaper
#      revision: main
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
