name: Build ZMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    uses: filterpaper/scripts/.github/workflows/build-user-config.yml@main
#    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  purge:
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
