name: Build ZMK firmware
on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3

    - name: Publish release
      uses: softprops/action-gh-release@master
      with:
        name: ZMK Firmware
        tag_name: latest
        draft: false
        prerelease: false
        files: "**/*.*"

  purge:
    if: github.event_name == 'schedule'
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
