name: Build ZMK firmware
on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    needs: build
    uses: filterpaper/scripts/.github/workflows/publish-artifact.yml@main
    with:
      release_name: ZMK Firmware
      release_tag: latest

  purge:
    if: github.event_name == 'schedule'
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
